version: "3.5"

services:

  rpc_master:
    image: robyn:master
    build:
      context: .
    restart: unless-stopped
    ports:
      - "5015:5015"


    volumes:
      - ./src:/usr/src:ro
      - ./src/static/logs:/usr/src/static/logs:rw
      - ./src/static/image:/usr/src/static/image:rw

    working_dir: /usr/src
    command: python3 -u main.py --workers 4

    networks:
      bridge-network:
        aliases:
          - master.local


networks:
  bridge-network:
    driver: bridge
    name: bridge-network

# networks:
#   swarm-overlay-network:
#     external: true
#     name: swarm-overlay-network
