version: '3.8'

services:
  rpc_slave:
    image: rpc:slave
    build:
      context: .
    
    restart: unless-stopped
    ports:
      - "4242:4242"
    volumes:
      - ./src:/usr/src:ro 
    working_dir: /usr/src
    command: python3 -u main.py
    
    networks:
      swarm-overlay-network:
        aliases:
          - rpc_slave.local

networks:
  swarm-overlay-network:
    external: true
    name: swarm-overlay-network 


 